In [20]:
import numpy as np
x = np.random.randint(0,100,7)
print("X: " + str(x))

a = [1,2,3,4,5]
l = a.append(8)
b = np.append(a[1:5],x)
print(b)


X: [97 55 92 12  9 64  1]
[ 2  3  4  5 97 55 92 12  9 64  1]


In [4]:
value = 0.66
print("Drosselklappe: " + str(int(value * 100)) + "%")

Drosselklappe: 66%


In [12]:
step = 0
print(step)



def triggerAlert(code):
    if code == "lessWood":
        #trigger push notification for adding new wood
        print("time to add more wood")
        
triggerAlert("lessWood")


0
time to add more wood


In [ ]:
import numpy as np
import time
from timeloop import Timeloop
from datetime import timedelta

a = [1,2,3,4,5]

tl = Timeloop()
tl.start(block=True)

@tl.job(interval=timedelta(seconds=2))
def sample_job_every_2s():   
    x = np.random.randint(0,100,1)[0]
    b = np.append(a[1:5],x)
    print(b)

@tl.job(interval=timedelta(seconds=10))
def stop():
    tl.stop()
    print("stop")

[2020-06-07 14:43:49,961] [timeloop] [INFO] Starting Timeloop..
[2020-06-07 14:43:49,962] [timeloop] [INFO] Timeloop now started. Jobs will run based on the interval set


In [17]:
a = [[11,2,3,4,5,6,7],[12,2,3,4,5,6,7]]
a.append([13,2,3,4,5,6,7])
print(len(a))
print(a)

l = a[len(a)-1]
print(l)


b = np.array(a)
print(b[1])

3
[[11, 2, 3, 4, 5, 6, 7], [12, 2, 3, 4, 5, 6, 7], [13, 2, 3, 4, 5, 6, 7]]
[13, 2, 3, 4, 5, 6, 7]
[12  2  3  4  5  6  7]


In [22]:
fan = 1.0
drosselklappe = 0.73
steamRegularizers = 0.0
currentTemp = 125.8

print("Fan: " + str(int(fan*100)) + "% ; Drosselklappe: " + str(int(drosselklappe*100)) + "% ; CurrentTemp: " + str(currentTemp) + "; SRZs: " + str(steamRegularizers)) 

Fan: 100% ; Drosselklappe: 73% ; CurrentTemp: 125.8; SRZs: 0.0


In [25]:
a = [0,1,2,3,4,5,6,7,8,9]
a.append(10)

length = 5
ind_start = len(a)-length
b = np.array(a[ind_start:])

print(b)

[ 6  7  8  9 10]


In [26]:
a=[1,2,3,4,5]
print(a[:3])

[1, 2, 3]


In [15]:
alertCodes= {"lesswood":False, "sensorerror":False, "programfail":False , "message":"none"}

print(str(alertCodes["lesswood"]) + alertCodes["message"])


Falsenone


In [18]:
i = 0
isSimulation = True
while(i < 10):
    i = i + 1
    if(isSimulation):
        print("Simulation: i = " + str(i) )
        continue
    print("No Simulatioln, i = " + str(i))
        

Simulation: i = 1
Simulation: i = 2
Simulation: i = 3
Simulation: i = 4
Simulation: i = 5
Simulation: i = 6
Simulation: i = 7
Simulation: i = 8
Simulation: i = 9
Simulation: i = 10


In [31]:
c = [11,22,33,44,55,66,77]
x = [111,222,333,444,555,666,777]


for idx, value in enumerate(x):
    print("Value:" + str(value))
    print("idx:" +str(c[idx]))    

Value:111
idx:11
Value:222
idx:22
Value:333
idx:33
Value:444
idx:44
Value:555
idx:55
Value:666
idx:66
Value:777
idx:77


In [9]:
import re
str2 = "b'Temp1:190.01-Temp2:120.02-Temp3:67.03'"
strr = "abcde"
print(str2)
#str = re.sub("b'","",str)
#str = re.sub("\r\n'","",str)
str2 = str2[2:]
str2 = str2[:-1]
print(str2)


if(str.lower() == "nan"):
    print("N")

b'Temp1:190.01-Temp2:120.02-Temp3:67.03'
Temp1:190.01-Temp2:120.02-Temp3:67.03


In [7]:
t2h = 300
ti = 47
m = 5
t_i1 = ti + m
reached = t_i1 / t2h  # Wert zwischen 0.0 und 1.0
print(reached)

# Neuen Wert für Lufteinlass berechnen
if reached <= 0.5:
    new_AirInput_value = 1.0



0.17333333333333334
